
const USERS = {
  LOAD: 'USERS_LOAD',
  LOAD_SUCCESS: 'USERS_LOAD_SUCCESS',
  LOAD_FAIL: 'USERS_LOAD_FAIL',
  SAVE_NEW: 'USERS_SAVE_NEW',
  SET_SNACKBAR_VALID: 'SET_SNACKBAR_VALID',
};

export { USERS };
